aws_dbt_snowflake_project:
  outputs:
    dev:
      account: WSESPOG-VO22181
      database: AIRBNB
      private_key_passphrase: tereayen123
      private_key_path: /Users/isumalde/snowflake_private_key.p8
      role: ACCOUNTADMIN
      schema: STAGING
      threads: 1
      type: snowflake
      user: IRENESUMALDE
      warehouse: COMPUTE_WH
  target: dev
